services:
  app:    
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/architect-portfolio:latest
    container_name: architect-portfolio
    ports:
      - 6000:3000
    networks:
      - ubuntu_default
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"
    restart: always

networks:
  ubuntu_default:
    external: true